site_name: 🥔 PotatoNetwork
site_description: Last-mile network emulator for Docker sidecars
repo_url: https://github.com/kriakiku/potato-inspector
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Light mode
nav:
  - Home: index.md
  - Overview: overview.md
  - API: api.md
  - Rules (expr): rules.md
  - CA: ca.md
  - Examples: examples.md
  - Profiles gallery: profiles-gallery.md
markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
